name: medquest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  outlined_text: ^1.0.1
  icons_launcher: ^3.0.1
  flutter_datetime_picker_plus: ^2.2.0
  supabase_flutter: ^2.10.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
     - images/
     
  fonts:
     - family: poppins
       fonts:
         - asset: fonts/Poppins-Black.ttf
           weight: 900
         - asset: fonts/Poppins-ExtraBold.ttf
           weight: 800            
         - asset: fonts/Poppins-Bold.ttf
           weight: 700           
         - asset: fonts/Poppins-SemiBold.ttf
           weight: 600

icons_launcher:
  image_path: "images/MQ.png"
  platforms:
    android:
      enable: true  